version: '2'
services:
    website:
        container_name: dbapp_php
        build:
            context: ./src
            dockerfile: Dockerfile
        volumes:
            - ./src:/app
        ports:
            - "9000:80"
    mysql:
        container_name: dbapp_mysql
        restart: always
        image: "mysql:5.7"
        environment:
            - MYSQL_HOST=127.0.0.1
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=dbapp
            - MYSQL_PASS=dbpass
            - MYSQL_DATABASE=employee_management
        volumes:
            - ./data/dump:/docker-entrypoint-initdb.d
            - ./data/db:/var/lib/mysql
        ports:
            - "3306:3306"
    mongodb:
        container_name: dbapp_mongo
        image: "mongo"
        restart: always
        volumes:
            - ./data/mongo:/data/db
        ports:
            - "27020:27017"
    phpmyadmin:
        container_name: dbapp_admin
        restart: always
        image: "phpmyadmin/phpmyadmin"
        ports:
            - "8080:80"
        environment:
            - PMA_HOST=dbapp_mysql
            - MYSQL_ROOT_PASSWORD=root
